sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t "$DOCKER_ID"/react-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true "$DOCKER_ID"/react-client-test npm test

after_success:
  - docker build -t jmcausing1/multi-client ./client
  - docker build -t jmcausing1/multi-nginx ./nginx
  - docker build -t jmcausing1/multi-server ./server
  - docker build -t jmcausing1/multi-worker ./worker
  # Login into docker hub.
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub.
  - docker push jmcausing1/multi-client
  - docker push jmcausing1/multi-nginx
  - docker push jmcausing1/multi-server
  - docker push jmcausing1/multi-worker
deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'multi-docker2'
  env: 'Multidocker2-env'
  bucket_name: 'elasticbeanstalk-us-west-2-860399643556'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY