version: "3"
services:
  client:
    image: "jmcausing1/multi-client"
    mem_limit: 128m
    hostname: client
  api:
    image: "jmcausing1/multi-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  worker:
    image: "jmcausing1/multi-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "jmcausing1/multi-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
